modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="firmalife" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Firmalife" #mandatory
logoFile="firmalife.png" #optional
authors="EERussianguy" #optional
description='''
An addon for TFC.
'''
[[dependencies.firmalife]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.firmalife]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.firmalife]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"
